/**
 * Weapon Registry — Static config for all weapons
 */

import { type WeaponId, type WeaponConfig } from '../types/weapons';

export const WEAPON_REGISTRY: Record<WeaponId, WeaponConfig> = {
  quantum_bullet: {
    id: 'quantum_bullet',
    name: 'Quantum Bullet',
    icon: '🔫',
    description: 'Default rapid-fire projectile',
    baseDamage: 25,
    baseCooldown: 400,
    projectileSpeed: 8,
    projectileRadius: 5,
    projectileCount: 1,
    damagePerLevel: 0.25,
    cooldownPerLevel: 0.08,
    marketBonus: () => 1.0,
    behavior: 'targeted',
    evolutionPair: 'laser',
    evolutionResult: 'hyper_cannon',
    visual: {
      renderKind: 'quantum',
      params: {
        trailLifeMs: 180,
        coreColor: '#22d3ee',
        glowColor: '#22d3ee',
        trailMaxPoints: 16,
      },
    },
  },
  hyper_cannon: {
    id: 'hyper_cannon',
    name: 'Hyper Cannon',
    icon: '⚡',
    description: 'Evolved quantum-laser cannon with dense focused fire',
    baseDamage: 18,
    baseCooldown: 300,
    projectileSpeed: 9,
    projectileRadius: 6,
    projectileCount: 5,
    damagePerLevel: 0.16,
    cooldownPerLevel: 0.04,
    marketBonus: ({ atrPercent, isFavorable }) =>
      1.15 + Math.min(atrPercent / 0.03, 1) * 0.35 + (isFavorable ? 0.15 : 0),
    behavior: 'spread',
    spreadAngle: 0.08,
    visual: {
      renderKind: 'quantum',
      params: {
        trailLifeMs: 220,
        coreColor: '#ffffff',
        glowColor: '#67e8f9',
        trailMaxPoints: 18,
      },
    },
  },
  spread_shot: {
    id: 'spread_shot',
    name: 'Spread Shot',
    icon: '🔫',
    description: '3-way fan fire, volume bonus',
    baseDamage: 18,
    baseCooldown: 500,
    projectileSpeed: 7,
    projectileRadius: 4,
    projectileCount: 3,
    damagePerLevel: 0.2,
    cooldownPerLevel: 0.08,
    marketBonus: ({ volumeNorm }) => 1.0 + (volumeNorm > 0.7 ? 0.3 : 0),
    behavior: 'spread',
    spreadAngle: 0.4,
    visual: {
      renderKind: 'spread',
      params: {
        trailLifeMs: 200,
        coolColor: '#ffd060',
        hotColor: '#ffff88',
        coolTrailRgb: '255,180,80',
        hotTrailRgb: '255,220,120',
        trailMaxPoints: 16,
        heatThreshold: 0.7,
      },
    },
  },
  laser: {
    id: 'laser',
    name: 'Volatility Laser',
    icon: '⚡',
    description: 'Segmented beam, ATR-driven damage',
    baseDamage: 10,
    baseCooldown: 900,
    projectileSpeed: 0,
    projectileRadius: 8,
    projectileCount: 1,
    damagePerLevel: 0.2,
    cooldownPerLevel: 0.04,
    marketBonus: ({ atrPercent }) => 0.7 + Math.min(atrPercent / 0.03, 1) * 0.8,
    behavior: 'laser',
    evolutionPair: 'quantum_bullet',
    evolutionResult: 'hyper_cannon',
    visual: {
      renderKind: 'laser',
      params: {
        beamLifeMs: 160,
        beamSegmentLength: 44,
        beamSegmentSpacing: 30,
      },
    },
  },
  boomerang: {
    id: 'boomerang',
    name: 'RSI Boomerang',
    icon: '🪃',
    description: 'Returns to player, hits twice',
    baseDamage: 30,
    baseCooldown: 1300,
    projectileSpeed: 7,
    projectileRadius: 8,
    projectileCount: 1,
    damagePerLevel: 0.16,
    cooldownPerLevel: 0.06,
    marketBonus: ({ isFavorable }) => (isFavorable ? 1.45 : 1.0),
    behavior: 'boomerang',
    visual: {
      renderKind: 'boomerang',
      params: {
        trailLifeMs: 380,
        flightLifeMs: 1550,
      },
    },
  },
  aoe_nuke: {
    id: 'aoe_nuke',
    name: 'AOE Nuke',
    icon: '💥',
    description: 'Slow, massive explosion radius',
    baseDamage: 50,
    baseCooldown: 3200,
    projectileSpeed: 3,
    projectileRadius: 10,
    projectileCount: 1,
    damagePerLevel: 0.15,
    cooldownPerLevel: 0.04,
    marketBonus: ({ pnl }) => (pnl < -0.3 ? 1.35 : 1.0),
    behavior: 'nuke',
    visual: {
      renderKind: 'nuke',
      params: {
        flightMaxMs: 2400,
        shockwaveLifeMs: 650,
        shockwaveRadius: 68,
      },
    },
  },
  orbit_shield: {
    id: 'orbit_shield',
    name: 'Orbit Shield',
    icon: '🛡️',
    description: 'Persistent orbiters that damage nearby enemies',
    baseDamage: 8,
    baseCooldown: 1000,
    projectileSpeed: 0,
    projectileRadius: 11,
    projectileCount: 2,
    damagePerLevel: 0.18,
    cooldownPerLevel: 0,
    marketBonus: ({ pnl }) => (pnl > 0 ? 1.2 : 1.0),
    behavior: 'orbit',
    visual: {
      renderKind: 'orbit',
      params: {
        orbitRadius: 55,
        orbitSpeed: 0.0035,
      },
    },
  },
};

export const WEAPON_LIST = Object.values(WEAPON_REGISTRY);
