/**
 * Weapon Registry — Static config for all weapons
 */

import { type WeaponId, type WeaponConfig } from '../types/weapons';

export const WEAPON_REGISTRY: Record<WeaponId, WeaponConfig> = {
  quantum_bullet: {
    id: 'quantum_bullet',
    name: 'Quantum Bullet',
    icon: '🔫',
    description: 'Default rapid-fire projectile',
    baseDamage: 25,
    baseCooldown: 400,
    projectileSpeed: 8,
    projectileRadius: 5,
    projectileCount: 1,
    damagePerLevel: 0.25,
    cooldownPerLevel: 0.08,
    marketBonus: () => 1.0,
    behavior: 'targeted',
    evolutionPair: 'laser',
    evolutionResult: 'hyper_cannon',
    visual: {
      renderKind: 'quantum',
      params: {
        trailLifeMs: 180,
        coreColor: '#22d3ee',
        glowColor: '#22d3ee',
        trailMaxPoints: 16,
      },
    },
  },
  spread_shot: {
    id: 'spread_shot',
    name: 'Spread Shot',
    icon: '🔫',
    description: '3-way fan fire, volume bonus',
    baseDamage: 18,
    baseCooldown: 500,
    projectileSpeed: 7,
    projectileRadius: 4,
    projectileCount: 3,
    damagePerLevel: 0.2,
    cooldownPerLevel: 0.08,
    marketBonus: ({ volumeNorm }) => 1.0 + (volumeNorm > 0.7 ? 0.3 : 0),
    behavior: 'spread',
    spreadAngle: 0.4,
    visual: {
      renderKind: 'spread',
      params: {
        trailLifeMs: 200,
        coolColor: '#ffd060',
        hotColor: '#ffff88',
        coolTrailRgb: '255,180,80',
        hotTrailRgb: '255,220,120',
        trailMaxPoints: 16,
        heatThreshold: 0.7,
      },
    },
  },
  laser: {
    id: 'laser',
    name: 'Volatility Laser',
    icon: '⚡',
    description: 'Rapid-fire beam, ATR-driven damage',
    baseDamage: 6,
    baseCooldown: 250,
    projectileSpeed: 14,
    projectileRadius: 3,
    projectileCount: 1,
    damagePerLevel: 0.2,
    cooldownPerLevel: 0,
    marketBonus: ({ atrPercent }) => 0.7 + Math.min(atrPercent / 0.03, 1) * 0.8,
    behavior: 'targeted',
    evolutionPair: 'quantum_bullet',
    evolutionResult: 'hyper_cannon',
    visual: { renderKind: 'default' },
  },
  boomerang: {
    id: 'boomerang',
    name: 'RSI Boomerang',
    icon: '🪃',
    description: 'Returns to player, hits twice',
    baseDamage: 35,
    baseCooldown: 1200,
    projectileSpeed: 6,
    projectileRadius: 8,
    projectileCount: 1,
    damagePerLevel: 0.2,
    cooldownPerLevel: 0.1,
    marketBonus: ({ isFavorable }) => (isFavorable ? 2.0 : 1.0),
    behavior: 'targeted',
    visual: { renderKind: 'default' },
  },
  aoe_nuke: {
    id: 'aoe_nuke',
    name: 'AOE Nuke',
    icon: '💥',
    description: 'Slow, massive explosion radius',
    baseDamage: 60,
    baseCooldown: 3000,
    projectileSpeed: 3,
    projectileRadius: 40,
    projectileCount: 1,
    damagePerLevel: 0.15,
    cooldownPerLevel: 0.06,
    marketBonus: ({ pnl }) => (pnl < -0.3 ? 1.5 : 1.0),
    behavior: 'targeted',
    visual: { renderKind: 'default' },
  },
  orbit_shield: {
    id: 'orbit_shield',
    name: 'Orbit Shield',
    icon: '🛡️',
    description: 'Burst of projectiles in all directions',
    baseDamage: 15,
    baseCooldown: 2000,
    projectileSpeed: 5,
    projectileRadius: 6,
    projectileCount: 3,
    damagePerLevel: 0.25,
    cooldownPerLevel: 0.05,
    marketBonus: ({ pnl }) => (pnl > 0 ? 1.3 : 1.0),
    behavior: 'burst',
    visual: { renderKind: 'default' },
  },
};

export const WEAPON_LIST = Object.values(WEAPON_REGISTRY);
