/**
 * ErrorTracker - Enhanced Client-Side Error Tracking (Refactored)
 *
 * This is a thin orchestrator that delegates to focused modules:
 * - ErrorTypes.ts - Type definitions and constants
 * - ErrorQueue.ts - Offline queue management
 * - ErrorSanitizer.ts - Privacy-safe sanitization
 *
 * Features:
 * - Global error handler (window.onerror + unhandledrejection)
 * - Network error tracking with request/response details
 * - Performance issue detection
 * - Supabase integration for centralized logging
 * - Rate limiting & error deduplication
 * - Offline queue support with localStorage persistence
 * - Privacy-safe error sanitization
 * - User action breadcrumbs (last N actions before error)
 * - Error grouping by fingerprint
 * - UUID validation for database integrity
 * - Game state context capture
 *
 * @refactored Split from 733-line monolith into focused modules
 */

import { Logger } from '../system/Logger';
import { UserSessionService } from '../auth/UserSessionService';

// Import from extracted modules
import {
  type ErrorReport,
  type ErrorSeverity,
  type ErrorCategory,
  type Breadcrumb,
  type GameContext,
  ERROR_CONSTANTS,
} from './ErrorTypes';
import { ErrorQueue } from './ErrorQueue';
import {
  createFingerprint,
  sanitizeMessage,
  sanitizeStackTrace,
  sanitizeUrl,
  sanitizeContext,
  getSessionId,
  getDeviceFingerprint,
} from './ErrorSanitizer';

// Re-export types for consumers
export type { ErrorReport, ErrorSeverity, ErrorCategory, Breadcrumb, GameContext };

// =============================================================================
// ERROR TRACKER CLASS
// =============================================================================

export class ErrorTracker {
  private static instance: ErrorTracker | null = null;

  // Extracted queue management
  private queue: ErrorQueue;

  // State
  private breadcrumbs: Breadcrumb[] = [];
  private recentErrors = new Map<string, number>();
  private isOnline = navigator.onLine;
  private sessionStartTime = Date.now();
  private gameContext: GameContext = {};
  private originalConsoleError: typeof console.error;
  private tags: string[] = [];
  private pendingPromises: Set<Promise<unknown>> = new Set();

  /** Circuit breaker: stop sending when Supabase quota is exhausted (402) */
  private circuitOpen = false;
  private circuitOpenedAt = 0;
  private static readonly CIRCUIT_COOLDOWN_MS = 5 * 60 * 1000; // 5 min

  // Handler references for cleanup
  private queueProcessorInterval: ReturnType<typeof setInterval> | null = null;
  private boundErrorHandler: ((event: ErrorEvent) => void) | null = null;
  private boundRejectionHandler: ((event: PromiseRejectionEvent) => void) | null = null;
  private boundOnlineHandler: (() => void) | null = null;
  private boundOfflineHandler: (() => void) | null = null;
  private boundResourceHandler: ((event: Event) => void) | null = null;

  // ==========================================================================
  // CONSTRUCTOR & SINGLETON
  // ==========================================================================

  private constructor() {
    this.originalConsoleError = console.error.bind(console);
    this.queue = new ErrorQueue();
    this.setupGlobalHandlers();
    this.setupNetworkMonitoring();
    this.setupResourceMonitoring();
    this.setupConsoleInterception();
    this.setupLoggerSubscription();
    this.startQueueProcessor();
    this.addBreadcrumb('system', 'ErrorTracker initialized');
  }

  static getInstance(): ErrorTracker {
    ErrorTracker.instance ??= new ErrorTracker();
    return ErrorTracker.instance;
  }

  // ==========================================================================
  // SUBSCRIPTIONS
  // ==========================================================================

  private setupLoggerSubscription(): void {
    Logger.onError((message, error, data) => {
      // Prevent infinite loops: Don't track errors generated by ErrorTracker
      if (message.includes('[ErrorTracker]')) {
        return;
      }

      void this.captureError({
        errorType: 'LoggerError',
        errorMessage: message,
        category: 'runtime',
        severity: 'medium',
        context:
          error instanceof Error
            ? { stack: error.stack, ...data }
            : { rawError: error, ...data },
      });
    });

    Logger.info('[ErrorTracker] Subscribed to Logger events');
  }

  // ==========================================================================
  // PUBLIC API
  // ==========================================================================

  captureError(options: {
    errorType: string;
    errorMessage: string;
    stackTrace?: string;
    category?: ErrorCategory;
    severity?: ErrorSeverity;
    context?: Record<string, unknown>;
    tags?: string[];
  }): void | Promise<void> {
    const {
      errorType,
      errorMessage,
      stackTrace,
      category = 'runtime',
      severity = 'medium',
      context,
      tags = [],
    } = options;

    // Create fingerprint for grouping
    const fingerprint = createFingerprint(errorType, errorMessage, stackTrace);

    // Rate limiting
    const lastReport = this.recentErrors.get(fingerprint);
    const now = Date.now();
    if (lastReport && now - lastReport < ERROR_CONSTANTS.RATE_LIMIT_MS) {
      Logger.debug(`[ErrorTracker] Rate limited: ${errorType}`);
      return Promise.resolve();
    }
    this.recentErrors.set(fingerprint, now);
    Logger.debug(`[ErrorTracker] captureError: ${errorType}`);

    // Build report
    const report: ErrorReport = {
      errorType,
      errorMessage: sanitizeMessage(errorMessage),
      stackTrace: sanitizeStackTrace(stackTrace),
      category,
      severity,
      fingerprint,
      userAgent: navigator.userAgent,
      url: window.location.href,
      viewport: { width: window.innerWidth, height: window.innerHeight },
      profileId: UserSessionService.getProfileId(),
      sessionId: getSessionId(),
      deviceFingerprint: getDeviceFingerprint(),
      nickname: UserSessionService.getNickname() ?? undefined,
      context: sanitizeContext(context),
      breadcrumbs: [...this.breadcrumbs],
      gameContext: { ...this.gameContext },
      reportedAt: new Date().toISOString(),
      sessionDurationMs: Date.now() - this.sessionStartTime,
      tags: [...this.tags, ...tags],
    };

    // Try to enrich with GameStore state (lazy avoid circular deps)
    const promise = import('../../stores/gameStore')
      .then(module => {
        const state = module.useGameStore.getState();
        report.gameContext = {
          ...report.gameContext,
          gameStatus: (window as { GAME_STATE?: string }).GAME_STATE ?? 'UNKNOWN',
          playerLevel: state.progress.highestLevel,
          survivalTimeMs: state.progress.bestSurvivalTime,
          // session info
          sessionId: state.session.sessionId,
        };

        // Also add some graphics info to context
        report.context ??= {};
        report.context.graphics = {
          fps: (window as { FPS_VALUE?: number }).FPS_VALUE ?? 0,
          particles: state.graphics.showParticles,
          mobile: state.mobile.controlType === 'joystick',
        };
      })
      .catch(() => {})
      .finally(() => {
        // Queue or send after trying to get context
        Logger.debug(`[ErrorTracker] captureError finally: online=${this.isOnline}`);
        if (this.isOnline) {
          return this.sendError(report);
        } else {
          Logger.debug(`[ErrorTracker] captureError: queueing because offline`);
          this.queue.enqueue(report);
          return Promise.resolve();
        }
      });

    this.pendingPromises.add(promise);
    void promise.finally(() => this.pendingPromises.delete(promise));
    return promise;
  }

  /**
   * Wait for all pending async operations to complete
   */
  async flush(): Promise<void> {
    await Promise.all(this.pendingPromises);
  }

  /**
   * Capture network error with details
   */
  captureNetworkError(
    url: string,
    method: string,
    status: number,
    statusText: string,
    duration?: number
  ): void {
    void this.captureError({
      errorType: 'NetworkError',
      errorMessage: `${method} ${url} failed: ${status} ${statusText}`,
      category: 'network',
      severity: status >= 500 ? 'high' : 'medium',
      context: {
        url: sanitizeUrl(url),
        method,
        status,
        statusText,
        durationMs: duration,
      },
      tags: ['network', `status-${status}`],
    });
  }

  /**
   * Capture performance issue
   */
  capturePerformanceIssue(
    metric: string,
    value: number,
    threshold: number,
    unit: string = ''
  ): void {
    void this.captureError({
      errorType: 'PerformanceIssue',
      errorMessage: `${metric} (${value}${unit}) exceeded threshold (${threshold}${unit})`,
      category: 'performance',
      severity: value > threshold * 2 ? 'high' : 'low',
      context: {
        metric,
        value,
        threshold,
        exceeded: value - threshold,
        exceedPercent: Math.round(((value - threshold) / threshold) * 100),
      },
      tags: ['performance', metric.toLowerCase().replace(/\s/g, '-')],
    });
  }

  /**
   * Capture game-specific error
   */
  captureGameError(
    errorType: string,
    message: string,
    gameData?: Record<string, unknown>
  ): void {
    void this.captureError({
      errorType,
      errorMessage: message,
      category: 'game',
      severity: 'medium',
      context: gameData,
      tags: ['game'],
    });
  }

  /**
   * Add breadcrumb (user action tracking)
   */
  addBreadcrumb(
    category: string,
    message: string,
    data?: Record<string, unknown>
  ): void {
    this.breadcrumbs.push({
      timestamp: Date.now(),
      category,
      message,
      data,
    });

    // Keep only last N
    if (this.breadcrumbs.length > ERROR_CONSTANTS.MAX_BREADCRUMBS) {
      this.breadcrumbs.shift();
    }
  }

  /**
   * Update game context (called by game systems)
   */
  setGameContext(context: Partial<GameContext>): void {
    this.gameContext = { ...this.gameContext, ...context };
  }

  /**
   * Add global tag
   */
  addTag(tag: string): void {
    if (!this.tags.includes(tag)) {
      this.tags.push(tag);
    }
  }

  /**
   * Remove global tag
   */
  removeTag(tag: string): void {
    const index = this.tags.indexOf(tag);
    if (index !== -1) {
      this.tags.splice(index, 1);
    }
  }

  /**
   * Get error statistics
   */
  getStats(): {
    queueSize: number;
    recentErrorsCount: number;
    breadcrumbsCount: number;
    sessionDurationMs: number;
  } {
    return {
      queueSize: this.queue.size,
      recentErrorsCount: this.recentErrors.size,
      breadcrumbsCount: this.breadcrumbs.length,
      sessionDurationMs: Date.now() - this.sessionStartTime,
    };
  }

  // ==========================================================================
  // SETUP METHODS
  // ==========================================================================

  private setupGlobalHandlers(): void {
    this.boundErrorHandler = (event: ErrorEvent) => {
      void this.captureError({
        errorType: 'UnhandledError',
        errorMessage: event.message || 'Unknown error',
        stackTrace: event.error?.stack,
        category: 'runtime',
        severity: 'high',
        context: {
          filename: event.filename,
          lineno: event.lineno,
          colno: event.colno,
        },
        tags: ['unhandled'],
      });
    };

    this.boundRejectionHandler = (event: PromiseRejectionEvent) => {
      const message = event.reason?.message ?? String(event.reason);
      void this.captureError({
        errorType: 'UnhandledPromiseRejection',
        errorMessage: message,
        stackTrace: event.reason?.stack,
        category: 'runtime',
        severity: 'high',
        context: {
          promiseReason: String(event.reason).substring(0, 200),
        },
        tags: ['unhandled', 'promise'],
      });
    };

    window.addEventListener('error', this.boundErrorHandler);
    window.addEventListener('unhandledrejection', this.boundRejectionHandler);

    Logger.info('[ErrorTracker] Global error handlers installed');
  }

  private setupNetworkMonitoring(): void {
    this.boundOnlineHandler = () => {
      this.isOnline = true;
      this.addBreadcrumb('network', 'Online');
      Logger.info('[ErrorTracker] Network online - processing queue');
      void this.processQueue();
    };

    this.boundOfflineHandler = () => {
      this.isOnline = false;
      this.addBreadcrumb('network', 'Offline');
      Logger.warn('[ErrorTracker] Network offline - queueing errors');
    };

    window.addEventListener('online', this.boundOnlineHandler);
    window.addEventListener('offline', this.boundOfflineHandler);

    // Intercept fetch
    const originalFetch = window.fetch;
    window.fetch = async (input: RequestInfo | URL, init?: RequestInit) => {
      const startTime = Date.now();
      const url =
        typeof input === 'string'
          ? input
          : input instanceof URL
            ? input.href
            : input.url;
      const method = init?.method ?? 'GET';

      try {
        const response = await originalFetch(input, init);
        const duration = Date.now() - startTime;

        // Track slow requests
        if (duration > 5000) {
          this.addBreadcrumb(
            'network',
            `Slow request: ${method} ${url} (${duration}ms)`
          );
        }

        // Track failed requests (but not telemetry errors to prevent loops)
        if (!response.ok && !url.includes('/telemetry/')) {
          Logger.debug(
            `[ErrorTracker] fetch failed detected: ${url} status: ${response.status}`
          );
          this.captureNetworkError(
            url,
            method,
            response.status,
            response.statusText,
            duration
          );
        }

        return response;
      } catch (error) {
        const duration = Date.now() - startTime;
        if (!url.includes('/telemetry/')) {
          this.captureNetworkError(url, method, 0, (error as Error).message, duration);
        }
        throw error;
      }
    };
  }

  private setupResourceMonitoring(): void {
    this.boundResourceHandler = (event: Event) => {
      const target = event.target;
      if (target && target instanceof Element && 'src' in target) {
        const src = (target as HTMLImageElement | HTMLScriptElement).src;
        void this.captureError({
          errorType: 'ResourceLoadError',
          errorMessage: `Failed to load resource: ${src}`,
          category: 'resource',
          severity: 'low',
          context: {
            tagName: target.tagName,
            src: sanitizeUrl(src),
          },
          tags: ['resource', target.tagName.toLowerCase()],
        });
      }
    };

    window.addEventListener('error', this.boundResourceHandler, true);
  }

  private setupConsoleInterception(): void {
    console.error = (...args: unknown[]) => {
      // Call original
      this.originalConsoleError(...args);

      // Capture as error
      const message = args
        .map(arg =>
          typeof arg === 'object' ? JSON.stringify(arg).substring(0, 200) : String(arg)
        )
        .join(' ');

      // Don't capture our own logs or filtered info/debug logs
      if (
        !message.includes('[ErrorTracker]') &&
        !message.includes('ℹ️') &&
        !message.includes('🔍')
      ) {
        void this.captureError({
          errorType: 'ConsoleError',
          errorMessage: message,
          category: 'console',
          severity: 'medium',
          tags: ['console'],
        });
      }
    };
  }

  private startQueueProcessor(): void {
    this.queueProcessorInterval = setInterval(() => {
      if (this.isOnline && !this.queue.isEmpty) {
        void this.processQueue();
      }
    }, ERROR_CONSTANTS.QUEUE_PROCESS_INTERVAL_MS);
  }

  // ==========================================================================
  // QUEUE & SEND
  // ==========================================================================

  private isCircuitOpen(): boolean {
    if (!this.circuitOpen) return false;
    // Auto-reset after cooldown
    if (Date.now() - this.circuitOpenedAt > ErrorTracker.CIRCUIT_COOLDOWN_MS) {
      this.circuitOpen = false;
      Logger.debug('[ErrorTracker] Circuit breaker reset — retrying error reporting');
      return false;
    }
    return true;
  }

  private async sendError(report: ErrorReport): Promise<void> {
    if (this.isCircuitOpen()) {
      this.queue.enqueue(report);
      return;
    }

    const railwayUrl = import.meta.env.VITE_RAILWAY_API_URL as string | undefined;
    if (!railwayUrl) {
      this.queue.enqueue(report);
      return;
    }

    try {
      const res = await fetch(`${railwayUrl}/api/v1/telemetry/errors`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          errorType: report.errorType,
          errorMessage: report.errorMessage,
          stackTrace: report.stackTrace,
          severity: report.severity,
          category: report.category,
          url: report.url,
          userAgent: report.userAgent,
          context: {
            ...report.context,
            viewport: report.viewport,
            nickname: report.nickname,
            gameContext: report.gameContext,
            breadcrumbs: report.breadcrumbs.slice(-10),
            tags: report.tags,
            sessionDurationMs: report.sessionDurationMs,
            fingerprint: report.fingerprint,
            deviceFingerprint: report.deviceFingerprint,
          },
        }),
      });

      if (!res.ok) {
        if (res.status === 402 || res.status === 429) {
          this.circuitOpen = true;
          this.circuitOpenedAt = Date.now();
          this.originalConsoleError(
            '[ErrorTracker] Rate limited. Circuit breaker open — suppressing sends for 5 minutes.'
          );
          return;
        }
        throw new Error(`HTTP ${res.status}`);
      }
    } catch (err) {
      this.originalConsoleError('[ErrorTracker] Failed to send error report:', err);
      this.queue.enqueue(report);
    }
  }

  private async processQueue(): Promise<void> {
    if (this.queue.isEmpty || this.isCircuitOpen()) return;

    const batch = this.queue.getBatch();

    for (const item of batch) {
      try {
        await this.sendError(item.report);
      } catch {
        this.queue.requeue(item);
      }
    }

    this.queue.persist();
  }

  // ==========================================================================
  // TESTING UTILITIES
  // ==========================================================================

  /**
   * Reset for testing purposes - proper cleanup
   */
  static resetForTesting(): void {
    if (this.instance) {
      // Restore original console.error
      console.error = this.instance.originalConsoleError;

      // Clear interval
      if (this.instance.queueProcessorInterval) {
        clearInterval(this.instance.queueProcessorInterval);
      }

      // Remove event listeners
      if (this.instance.boundErrorHandler) {
        window.removeEventListener('error', this.instance.boundErrorHandler);
      }
      if (this.instance.boundRejectionHandler) {
        window.removeEventListener(
          'unhandledrejection',
          this.instance.boundRejectionHandler
        );
      }
      if (this.instance.boundOnlineHandler) {
        window.removeEventListener('online', this.instance.boundOnlineHandler);
      }
      if (this.instance.boundOfflineHandler) {
        window.removeEventListener('offline', this.instance.boundOfflineHandler);
      }
      if (this.instance.boundResourceHandler) {
        window.removeEventListener('error', this.instance.boundResourceHandler, true);
      }

      // Clear queue
      this.instance.queue.clear();

      this.instance = null;
    }
  }
}

// Auto-initialize on import
const errorTracker = ErrorTracker.getInstance();
export default errorTracker;
