export const WORLD_SNAPSHOT_SCHEMA_VERSION = 1 as const;

export type WorldSnapshot = Readonly<{
  schemaVersion: typeof WORLD_SNAPSHOT_SCHEMA_VERSION;
  capacity: number;
  activeCount: number;
  freeSlotCount: number;
  freeSlots: Uint16Array;
  generations: Uint32Array;
  masks: Uint32Array;
  x: Float32Array;
  y: Float32Array;
  previousX: Float32Array;
  previousY: Float32Array;
  velocityX: Float32Array;
  velocityY: Float32Array;
  radius: Float32Array;
  health: Float32Array;
  maxHealth: Float32Array;
  faction: Int8Array;
  moveSpeed: Float32Array;
  lastFacingX: Float32Array;
  lastFacingY: Float32Array;
  dashDirectionX: Float32Array;
  dashDirectionY: Float32Array;
  dashRemainingSeconds: Float32Array;
  invulnerabilityTicksRemaining: Uint16Array;
  dashCooldownTicksRemaining: Uint16Array;
  dashCharges: Uint8Array;
  movementOverride: Uint8Array;
  enemySpeed: Float32Array;
  contactDamage: Float32Array;
  contactCooldownTicksRemaining: Uint16Array;
  xpValue: Float32Array;
  projectileDamage: Float32Array;
  projectileLifetimeTicksRemaining: Uint16Array;
  weaponCooldownTicksRemaining: Uint16Array;
  weaponDamage: Float32Array;
  xp: Float32Array;
  level: Uint16Array;
  xpPickupValue: Float32Array;
}>;
