import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { LEVERAGE_OPTIONS } from '../types';
import { DIRECTOR_CONFIG_V1 } from '../services/director/config/DirectorConfigV1';
import {
  ENCOUNTER_COST_UNITS,
  ENEMY_COST_UNITS,
} from '../services/director/encounters/EnemyCostCatalog';
import { ENCOUNTER_CARD_CATALOG } from '../services/director/encounters/EncounterCatalog';
import { ADVANTAGE_CARD_CATALOG } from '../services/director/encounters/AdvantageCatalog';

const targetPath = resolve(
  process.cwd(),
  'services/director/config/DirectorContentManifest.ts'
);

const manifestPayload = {
  directorConfig: {
    ...DIRECTOR_CONFIG_V1,
    versions: {
      ...DIRECTOR_CONFIG_V1.versions,
      contentManifestHash: '',
    },
  },
  enemyCosts: ENEMY_COST_UNITS,
  encounterCosts: ENCOUNTER_COST_UNITS,
  encounters: ENCOUNTER_CARD_CATALOG,
  advantages: ADVANTAGE_CARD_CATALOG,
  publicLeverageTiers: LEVERAGE_OPTIONS,
};
const hash = createHash('sha256').update(JSON.stringify(manifestPayload)).digest('hex');
const generatedSource = `/** Generated by scripts/generate-director-manifest.ts. */\nexport const DIRECTOR_CONTENT_MANIFEST_HASH =\n  '${hash}';\n`;

if (process.argv.includes('--check')) {
  const committedSource = readFileSync(targetPath, 'utf8').replaceAll('\r\n', '\n');
  if (committedSource !== generatedSource) {
    throw new Error(
      'Director content manifest is stale. Run npm run generate:director-manifest.'
    );
  }
} else {
  writeFileSync(targetPath, generatedSource, 'utf8');
}
