export const SIMULATION_HZ = 60;
export const SIMULATION_STEP_MS = 1000 / SIMULATION_HZ;
export const MAX_RENDER_DELTA_MS = 250;
export const MAX_CATCH_UP_STEPS = 8;
export const MVP0_CONFIG_VERSION = 1 as const;
export const INPUT_RECORDING_CAPACITY = 216_000;
export const COMMAND_RECORDING_CAPACITY = 64;
export const MAX_WORLD_CAPACITY = 4096;
export const TOP_DOWN_CAMERA_VISIBLE_HEIGHT = 18;
export const TOP_DOWN_CAMERA_NEAR = 0.1;
export const TOP_DOWN_CAMERA_FAR = 200;
export const TOP_DOWN_CAMERA_HEIGHT = 40;
export const TOP_DOWN_CAMERA_UP_X = 0;
export const TOP_DOWN_CAMERA_UP_Y = 0;
export const TOP_DOWN_CAMERA_UP_Z = -1;
export const PLAYER_MOVE_SPEED = 6;
export const DASH_SPEED = 16;
export const DASH_DURATION_SECONDS = 0.18;
export const DASH_INVULNERABILITY_SECONDS = 0.18;
export const DASH_COOLDOWN_SECONDS = 2.5;
export const DASH_INVULNERABILITY_TICKS = Math.ceil(
  DASH_INVULNERABILITY_SECONDS * SIMULATION_HZ
);
export const DASH_COOLDOWN_TICKS = Math.ceil(DASH_COOLDOWN_SECONDS * SIMULATION_HZ);
export const ENEMY_HEALTH = 30;
export const ENEMY_RADIUS = 0.6;
export const ENEMY_MOVE_SPEED = 2.2;
export const ENEMY_CONTACT_DAMAGE = 15;
export const ENEMY_XP_VALUE = 5;
export const ENEMY_FACTION = -1;
export const WEAPON_RANGE = 12;
export const WEAPON_COOLDOWN_SECONDS = 0.5;
export const WEAPON_COOLDOWN_TICKS = Math.ceil(WEAPON_COOLDOWN_SECONDS * SIMULATION_HZ);
export const PROJECTILE_SPEED = 14;
export const PROJECTILE_DAMAGE = 10;
export const PROJECTILE_RADIUS = 0.2;
export const PROJECTILE_LIFETIME_SECONDS = 1.5;
export const PROJECTILE_LIFETIME_TICKS = Math.ceil(
  PROJECTILE_LIFETIME_SECONDS * SIMULATION_HZ
);
export const PLAYER_RADIUS = 0.5;
export const PLAYER_MAX_HEALTH = 100;
export const ENEMY_CONTACT_COOLDOWN_SECONDS = 1.0;
export const ENEMY_CONTACT_COOLDOWN_TICKS = Math.ceil(
  ENEMY_CONTACT_COOLDOWN_SECONDS * SIMULATION_HZ
);
export const COMBAT_KILL_BUFFER_CAPACITY = 32;
