const MAX_SAFE_REVISION = Number.MAX_SAFE_INTEGER;

export const DIFFICULTY_RUNTIME_CONFIG = {
  versions: {
    algorithm: 'modular-difficulty-v1',
    config: 'modular-difficulty-config-v1',
  },
  ranges: {
    revision: { minimum: 0, maximum: MAX_SAFE_REVISION, integer: true },
    tick: { minimum: 0, maximum: MAX_SAFE_REVISION, integer: true },
    inputRevision: { minimum: 0, maximum: MAX_SAFE_REVISION, integer: true },
    sourceSequence: { minimum: 0, maximum: MAX_SAFE_REVISION, integer: true },
    seed: { minimum: 0, maximum: 4_294_967_295, integer: true },
    unitInterval: { minimum: 0, maximum: 1, integer: false },
    alignment: { minimum: -1, maximum: 1, integer: false },
    challengeAdjustment: { minimum: -1, maximum: 1, integer: false },
    killsPerMinute: { minimum: 0, maximum: 600, integer: false },
    creditRate: { minimum: 0, maximum: 1_000, integer: false },
    credits: { minimum: 0, maximum: 100_000, integer: false },
    durationSeconds: { minimum: 0, maximum: 3_600, integer: false },
    activeEnemyCount: { minimum: 0, maximum: 1_000, integer: true },
    behaviorTier: { minimum: 0, maximum: 10, integer: true },
    enemyHealthMultiplier: { minimum: 0.5, maximum: 5, integer: false },
    enemyDamageMultiplier: { minimum: 0.25, maximum: 4, integer: false },
    enemySpeedMultiplier: { minimum: 0.5, maximum: 3, integer: false },
    enemyVarietyMultiplier: { minimum: 0.5, maximum: 3, integer: false },
    rewardMultiplier: { minimum: 0.25, maximum: 4, integer: false },
    suggestedBpm: { minimum: 0, maximum: 240, integer: false },
  },
  neutral: {
    unitInterval: 0,
    multiplier: 1,
    count: 0,
    durationSeconds: 0,
    sourceSequence: 0,
    seed: 0,
    behaviorTier: 0,
    suggestedBpm: 0,
    quality: 'NEUTRAL',
    pressureBand: 'RELIEF',
    marketRegime: 'CALM',
    playerFlowState: 'FLOW',
    pacingPhase: 'BUILD_UP',
    encounterPhase: 'IDLE',
    reasonCode: 'NEUTRAL_INPUT',
  },
  reasonCodes: [
    'NEUTRAL_INPUT',
    'MARKET_LIVE',
    'MARKET_DELAYED',
    'MARKET_STALE',
    'MARKET_INVALID',
    'MARKET_OUT_OF_ORDER',
    'PLAYER_LIVE',
    'PLAYER_TELEMETRY_MISSING',
    'PLAYER_TELEMETRY_INVALID',
    'POSITION_NEUTRAL',
    'POSITION_FAVORABLE',
    'POSITION_HEADWIND',
    'POSITION_LIQUIDATION_RISK',
    'PACING_BUILD_UP',
    'PACING_PEAK',
    'PACING_PEAK_FADE',
    'PACING_RECOVERY',
    'PACING_MARKET_SURGE',
    'PACING_DOOM',
    'THREAT_NEUTRAL',
    'THREAT_RESERVED',
    'RECOVERY_NEUTRAL',
    'RECOVERY_MERCY',
    'ENCOUNTER_IDLE',
    'ENCOUNTER_TELEGRAPH',
    'ENCOUNTER_ACTIVE',
    'ENCOUNTER_RECOVERY',
    'ENCOUNTER_COOLDOWN',
    'RUN_NOT_INITIALIZED',
    'RUN_DUPLICATE',
    'RUN_CONSTANT_MISMATCH',
    'EVENT_REJECTED_NON_FINITE',
    'MANAGER_FAILURE_GRACE',
    'MANAGER_NEUTRAL_FALLBACK',
    'MARKET_NEUTRAL_FALLBACK',
    'PLAYER_NEUTRAL_FALLBACK',
    'POSITION_NEUTRAL_FALLBACK',
    'PACING_NEUTRAL_FALLBACK',
    'RECOVERY_NEUTRAL_FALLBACK',
    'ENCOUNTER_NEUTRAL_FALLBACK',
  ],
  clampCodes: [
    'PRESSURE_MINIMUM',
    'PRESSURE_MAXIMUM',
    'PACING_MINIMUM',
    'PACING_MAXIMUM',
    'PLAYER_SAFETY_MAXIMUM',
    'THREAT_CREDITS_MAXIMUM',
    'ADVANTAGE_CREDITS_MAXIMUM',
    'ACTIVE_ENEMY_MAXIMUM',
    'ENEMY_HEALTH_MINIMUM',
    'ENEMY_HEALTH_MAXIMUM',
    'ENEMY_DAMAGE_MINIMUM',
    'ENEMY_DAMAGE_MAXIMUM',
    'ENEMY_SPEED_MINIMUM',
    'ENEMY_SPEED_MAXIMUM',
    'REWARD_MINIMUM',
    'REWARD_MAXIMUM',
    'PRESENTATION_MAXIMUM',
  ],
  inbox: {
    damageWindowSeconds: 10,
    killWindowSeconds: 60,
    mobilityWindowSeconds: 15,
    marketDelayedAfterSeconds: 5,
    marketStaleAfterSeconds: 10,
  },
  pacing: {
    pressureBandWidth: 0.15,
  },
  player: {
    killsPerMinuteReference: 60,
    dashesPerMinuteReference: 12,
    shotsPerMinuteReference: 240,
    levelPowerReference: 25,
    stressedRecoveryThreshold: 0.55,
    boredEngagementThreshold: 0.25,
    telemetryWeights: {
      offenseMastery: 0.6,
      offenseBuild: 0.4,
      powerOffense: 0.65,
      powerHealth: 0.15,
      powerLevel: 0.2,
      counterScreenRelief: 0.35,
      rangedScreenRelief: 0.2,
    },
  },
  recovery: {
    maximumMercy: 0.6,
  },
  combination: {
    marketPressureWeight: 0.35,
    positionHeadwindWeight: 0.25,
    playerChallengeWeight: 0.25,
    requestedCreditsAtMaximumPressure: 12,
  },
  pressureBands: {
    reliefMaximum: 0.2,
    lowMaximum: 0.4,
    normalMaximum: 0.65,
    highMaximum: 0.85,
  },
  spawn: {
    minimumWindowSeconds: 0.4,
    maximumWindowSeconds: 2,
    maximumBehaviorTier: 4,
  },
  outputMapping: {
    enemyHealthPressureScale: 0.8,
    enemyDamagePressureScale: 0.5,
    enemySpeedPressureScale: 0.25,
    enemyVarietyPressureScale: 0.5,
    rewardPressureScale: 0.25,
    baseSuggestedBpm: 80,
    suggestedBpmRange: 80,
  },
  compatibility: {
    liquidationCautionThreshold: 0.35,
    liquidationDangerThreshold: 0.6,
    liquidationCriticalThreshold: 0.85,
    maximumFovReduction: 0.25,
    shockThreshold: 0.65,
    baseLootboxDropChance: 0.03,
    lootboxOpportunityScale: 0.02,
  },
  managerFailureGraceTicks: 3,
  traceCapacity: 256,
  shadowTolerances: {
    pressure: 0.025,
    multiplier: 0.025,
    cadenceSeconds: 0.05,
  },
} as const;
